### ISSUE TITLE
Support Consumption of Non-Webpacked Source Code

### ISSUE THREAD

**Issue by sbulley09** [ckeditor/ckeditor4-integrations-common#17]
## Are you reporting a feature request or a bug?
Feature Request

## Request Details
Currently, the only method of consumption is via the webpacked bundle in the dist folder. This webpack bundle includes a polyfill babel polyfill set up via the usage method. This ends up adding a polyfill for Promises but not for the 'finally' functionality of promises since those are not used within the code. One of our solutions relies on a promise polyfill which is a different polyfill than the provided by babel. 

Since the incomplete babel polyfill is loaded first without all the functionality, it doesn't get overwritten by our polypill and thus we end up with the 'finally' functionality missing. As a work around, we've copied the source code into our own project which allows us to use our internal strategy of building projects. This comes with the downside of having to continually update our internal fork over time and maintain that ourselves. It would be ideal for us to be able to consume the non-webpacked source and be able to apply our own polyfills as needed.

**Comment by sculpt0r** [comment]
Hi [**@sbulley09**](https://github.com/sbulley09) ,

Thank you for the proposal. At this point I can tell that we won't work on such a solution - so I close this issue. Please, notice that we have to provide a complete solution that works in many different environments.

**Comment by sculpt0r** [comment]
@sbulley09 base on https://github.com/ckeditor/ckeditor4-react/issues/180#issuecomment-796553902 I also reopen this issue.

**Comment by MMMalik** [comment]
Another downside of using webpack and including polyfills is a huge increase in bundle sizes. I would estimate the true size of `ckeditor4-integrations-common` to be just a few kilobytes when in fact this package (even minified) weighs around 21 KB. There is a huge potential gain in terms of bundle sizes for downstream packages and by consequence end-users. 

Since only integration libraries depend on this package, then fix should be easy to coordinate.
